# Generated by Django 3.1.1 on 2020-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PROFESSOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('Email_ID', models.TextField()),
                ('University', models.TextField()),
                ('Expertise', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('Email_ID', models.TextField()),
                ('University', models.TextField()),
                ('Branch', models.TextField()),
            ],
        ),
    ]
