# Generated by Django 3.1.1 on 2020-09-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ID',
        ),
    ]
